# Railway Nixpacks Configuration for Laravel
[phases.setup]
nixPkgs = ["...", "php84", "php84Extensions.pgsql", "php84Extensions.gd", "php84Extensions.zip", "php84Extensions.mbstring", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs",
    "npm ci",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan storage:link",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
