[nixpacks]
providers = ["php"] # Specify PHP as the provider

[nixpacks.phases.setup]
nixPkgs = ["...", "php83"] # Request PHP 8.3 package

[nixpacks.variables]
NIXPACKS_PHP_VERSION = "8.3" # Explicitly set the version variable
