services:
  - type: web
    name: ficct-horarios
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile.render
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: FICCT Horarios
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ficct-horarios-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ficct-horarios-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ficct-horarios-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ficct-horarios-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ficct-horarios-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_DRIVER
        value: database

databases:
  - name: ficct-horarios-db
    databaseName: ficct_horarios
    plan: free
    region: oregon
